package dev.minband.android

import dev.minband.core.FfiEdge
import dev.minband.core.FfiTrack

/**
 * Kotlin face of the Rust core (`core/src/ffi.rs`; bindings in `dev.minband.core`, generated by
 * `tools/build-android.sh`). All sync logic (ghosts, thresholds, budget controller, codec) runs in
 * Rust; this class converts types and keeps a bytes/s estimate for the HUD. Port of
 * ios/MinBand/EdgeBridge.swift.
 *
 * Thread-safe: `tick`/`stats`/`pose` run on the GL thread and `onDatagram` on the UDP receive
 * thread. The Rust object locks internally; the sample ring has its own lock.
 */
class EdgeBridge(deviceId: Int, sessionNonce: Int) {
    data class Stats(val seq: Long, val thetaScale: Double, val bytesPerSecEstimate: Int, val acked: Boolean, val budgetBps: Long)

    private val core = FfiEdge(deviceId.toUInt(), sessionNonce.toUInt())
    private val lock = Any()
    /** (edge tick, core bytesTotal) after every `tick`, oldest first; spans ~2 s once warmed up. */
    private val samples = ArrayDeque<Pair<Long, Long>>()

    /** Feed the tracker output at edge tick `now` (1/120 s since session start). Returns the datagrams to send right now (Hello until the server acks, then Delta/Keyframe). */
    fun tick(tracks: List<Track>, now: Long): List<ByteArray> {
        val out = core.tick(tracks.map(::ffiTrack), now.toUInt())
        record(now, core.stats().bytesTotal.toLong())
        return out
    }

    /** Datagram from the server (Ack: last seq, missing seqs for state repair, byte budget). */
    fun onDatagram(d: ByteArray) = core.onDatagram(d)

    fun stats(): Stats {
        val s = core.stats()
        return Stats(s.seq.toLong(), s.thetaScale.toDouble(), bytesPerSec(), s.acked, s.budgetBps.toLong())
    }

    /**
     * `Pose` datagram for the physical camera pose (camera -> world). Position is the camera
     * centre in the marker frame; orientation is a unit quaternion `[x, y, z, w]` (w last, w >= 0)
     * rotating camera-frame vectors into the marker frame. Returns an empty array until the server
     * has acked and whenever no Pose is due (the core derives the pose interval from the byte
     * budget); never send an empty datagram. A returned Pose consumes a seq.
     */
    fun pose(cameraToWorld: Mat4, origin: Origin, tick: Long): ByteArray {
        val p = origin.toMarker(cameraToWorld.origin)
        // (world -> marker) * (camera -> world) = camera -> marker.
        val q = (origin.rotationToMarker() * Quat.fromMatrix(cameraToWorld)).normalized().canonical()
        return core.encodePose(p.toList(), listOf(q.x, q.y, q.z, q.w), origin.isLocked, tick.toUInt())
    }

    private fun record(tick: Long, bytes: Long) = synchronized(lock) {
        val last = samples.lastOrNull()
        // Clock went backwards (ticks are u32 and wrap-compared like the core): start over.
        if (last != null && ((tick - last.first) and 0xFFFFFFFFL) > 0x7FFFFFFFL) samples.clear()
        samples.addLast(Pair(tick, bytes))
        while (samples.size > 2 && ((tick - samples[1].first) and 0xFFFFFFFFL) >= RATE_WINDOW) samples.removeFirst()
        while (samples.size > MAX_SAMPLES) samples.removeFirst()
    }

    /** Payload bytes/s over the last ~2 s of edge ticks (UDP/IP headers not included). */
    private fun bytesPerSec(): Int = synchronized(lock) {
        val first = samples.firstOrNull() ?: return 0
        val last = samples.last()
        if (last.first == first.first) return 0
        val seconds = ((last.first - first.first) and 0xFFFFFFFFL).toDouble() / TICKS_PER_SECOND
        return Math.round((last.second - first.second).toDouble() / seconds).toInt()
    }

    companion object {
        const val TICKS_PER_SECOND = 120L   // core TICK_HZ
        private const val RATE_WINDOW = 2 * TICKS_PER_SECOND
        private const val MAX_SAMPLES = 256

        private fun ffiTrack(t: Track) = FfiTrack(
            id = t.id.toUInt(), `class` = t.classId.toUByte(),
            pos = t.pos.toList(), vel = t.vel.toList(), conf = t.conf.toUByte(),
        )
    }
}
